###############################################################################
# imports
###############################################################################
tap 'homebrew/bundle'
tap 'homebrew/cask'
cask_args appdir: "~/Applications", require_sha: true
tap 'homebrew/cask-fonts'
tap 'homebrew/core'
tap 'homebrew/command-not-found'
tap 'warrensbox/tap'
tap 'hashicorp/tap'
tap 'neovim/neovim'

###############################################################################
# basics
###############################################################################
brew 'bash'
brew 'vim'
brew 'tmux'
brew 'git'
brew 'svn' # required for installin cask-fonts
brew 'mas' # Mac App Store Manager
brew 'mosh'
brew 'watch'
brew 'yt-dlp'

###############################################################################
# Utilities needed for Virtualbox Mac OS install
# https://github.com/myspaghetti/macos-virtualbox
###############################################################################
brew 'coreutils'
brew 'dmg2img'
brew 'gzip'
brew 'unzip'
brew 'wget'
brew 'docker-machine-driver-parallels'

###############################################################################
# dotfiles support
###############################################################################
brew 'stow'

###############################################################################
# hashicorp support
###############################################################################
brew 'tfswitch'

###############################################################################
# golang support
###############################################################################
brew 'go'

###############################################################################
# python support
###############################################################################
brew 'python'
brew 'pyenv-virtualenv'
brew 'pyenv-virtualenvwrapper'

###############################################################################
# ruby support
###############################################################################
brew 'rbenv'
brew 'rbenv-gemset'
brew 'ruby-build'

###############################################################################
# nodejs support
###############################################################################
brew 'nodenv'
brew 'node-build'

###############################################################################
# aws support
###############################################################################
brew 'awscli'

###############################################################################
# docker support
###############################################################################
cask 'docker'

###############################################################################
# utilities
###############################################################################
brew 'tree'
brew 'wget'
brew 'cmake'
brew 'shfmt'
brew 'nmap'
brew 'ripgrep'
brew 'inetutils'
brew 'jq'
brew 'trash'
brew 'vaulted'
brew 'shellcheck'
brew 'act'

###############################################################################
# fonts
###############################################################################
cask 'font-roboto-mono-for-powerline'
cask 'droid-sans-mono-nerd-font'
cask 'font-droid-sans-mono-for-powerline'
cask 'font-source-code-pro-for-powerline'
cask 'font-ubuntu-mono-derivative-powerline'
cask 'font-meslo-for-powerline'

###############################################################################
# apps
###############################################################################
cask 'discord'
cask 'transmit'
cask 'visual-studio-code'
cask 'tableplus'
cask 'slack'
cask 'keybase'
cask 'unite'
cask 'virtualbox'
cask 'iterm2'
#cask 'zoom'

mas 'Amphetamine', id: 937984704
mas 'WhatsApp Desktop', id: 1147396723

###############################################################################
# quicklook
###############################################################################
cask 'quicklook-json'
cask 'quicklook-csv'
#cask 'qlcolorcode' possible buggy or malicious

###############################################################################
# tap tools
###############################################################################
cask 'tunnelblick'

# taptools config
brew 'libsodium' # this is needed for the jwt (JSON Web Token) gem to run rspec tests

# Raynor config
brew 'direnv'
brew 'wget'
#brewset = ENV['BREWSET'] || 'minimal'
#cask 'virtualbox' unless brewset.to_sym.eql?(:minimal)
#cask 'virtualbox-extension-pack' unless brewset.to_sym.eql?(:minimal)
#cask 'vagrant' unless brewset.to_sym.eql?(:minimal)
#cask 'vagrant-manager' unless brewset.to_sym.eql?(:minimal)
#cask 'vagrant-vmware-utility' unless brewset.to_sym.eql?(:minimal)
#brew 'vagrant-completion' unless brewset.to_sym.eql?(:minimal)
